# Site settings
author: Melissa Hernandez
title: 
header-img: img/home-bg.png
email: hdez.melissaa@gmail.com
copyright_name: Melissa Hernandez
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: HdezMeli1686
github_username:  mahdesignstudio

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
